LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),cepheus)
ifeq ($(VIOLET_RECOVERY_DEFINED),)
VIOLET_RECOVERY_DEFINED := true
include $(CLEAR_VARS)
LOCAL_MODULE := predecrypt.sh
LOCAL_SRC_FILES := predecrypt.sh
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
include $(BUILD_PREBUILT)
endif
endif
